package org.uoa.bookshop.domain;

// Generated 2014-11-1 5:12:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private int bookid;
	private Catalog catalog;
	private String bookname;
	private int price;
	private String picture;
	private Set<Orderitem> orderitems = new HashSet<Orderitem>();

	public Book() {
	}

	public Book(int bookid, Catalog catalog, String bookname, int price,
			String picture) {
		this.bookid = bookid;
		this.catalog = catalog;
		this.bookname = bookname;
		this.price = price;
		this.picture = picture;
	}

	public Book(int bookid, Catalog catalog, String bookname, int price,
			String picture, Set<Orderitem> orderitems) {
		this.bookid = bookid;
		this.catalog = catalog;
		this.bookname = bookname;
		this.price = price;
		this.picture = picture;
		this.orderitems = orderitems;
	}

	public int getBookid() {
		return this.bookid;
	}

	public void setBookid(int bookid) {
		this.bookid = bookid;
	}

	public Catalog getCatalog() {
		return this.catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Set<Orderitem> getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set<Orderitem> orderitems) {
		this.orderitems = orderitems;
	}

}
