package org.uoa.bookshop.domain;

// Generated 2014-11-1 5:12:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Catalog generated by hbm2java
 */
public class Catalog implements java.io.Serializable {

	private int catalogid;
	private String catalogname;
	private Set<Book> books = new HashSet<Book>();

	public Catalog() {
	}

	public Catalog(int catalogid, String catalogname) {
		this.catalogid = catalogid;
		this.catalogname = catalogname;
	}

	public Catalog(int catalogid, String catalogname, Set<Book> books) {
		this.catalogid = catalogid;
		this.catalogname = catalogname;
		this.books = books;
	}

	public int getCatalogid() {
		return this.catalogid;
	}

	public void setCatalogid(int catalogid) {
		this.catalogid = catalogid;
	}

	public String getCatalogname() {
		return this.catalogname;
	}

	public void setCatalogname(String catalogname) {
		this.catalogname = catalogname;
	}

	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
