package org.uoa.bookshop.domain;

// Generated 2014-11-1 5:12:28 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int orderid;
	private User user;
	private Date orderdate;
	private Set<Orderitem> orderitems = new HashSet<Orderitem>();

	public Orders() {
	}

	public Orders(int orderid, User user, Date orderdate) {
		this.orderid = orderid;
		this.user = user;
		this.orderdate = orderdate;
	}

	public Orders(int orderid, User user, Date orderdate, Set<Orderitem> orderitems) {
		this.orderid = orderid;
		this.user = user;
		this.orderdate = orderdate;
		this.orderitems = orderitems;
	}

	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	public Set<Orderitem> getOrderitems() {
		return this.orderitems;
	}

	public void setOrderitems(Set<Orderitem> orderitems) {
		this.orderitems = orderitems;
	}

}
