package org.uoa.bookshop.domain;

// Generated 2014-11-1 5:12:28 by Hibernate Tools 4.0.0

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private int orderitemid;
	private Book book;
	private Orders orders;
	private int quantity;

	public Orderitem() {
	}

	public Orderitem(int orderitemid, Book book, Orders orders, int quantity) {
		this.orderitemid = orderitemid;
		this.book = book;
		this.orders = orders;
		this.quantity = quantity;
	}

	public int getOrderitemid() {
		return this.orderitemid;
	}

	public void setOrderitemid(int orderitemid) {
		this.orderitemid = orderitemid;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
