package org.uoa.bookshop.domain;

// Generated 2014-11-1 5:12:28 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userid;
	private String username;
	private String password;
	private String sex;
	private Integer age;
	private Set<Orders> orderses = new HashSet<Orders>();

	public User() {
	}

	public User(int userid, String username, String password) {
		this.userid = userid;
		this.username = username;
		this.password = password;
	}

	public User(int userid, String username, String password, String sex,
			Integer age, Set<Orders> orderses) {
		this.userid = userid;
		this.username = username;
		this.password = password;
		this.sex = sex;
		this.age = age;
		this.orderses = orderses;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
